@baseUrl = http://localhost:3001

# https://mockoon.com/tutorials/generate-mock-json-data/
###
GET {{baseUrl}}/faker-example

### queryParam example
GET {{baseUrl}}/faker-example?total=2

### switch command, with payload.status condition
GET {{baseUrl}}/switch-example
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "birthdate": "1956-10-10",
  "email": "john.doe@domain.com"
}

GET {{baseUrl}}/switch-example
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "birthdate": "1956-10-10",
  "email": "john.doe@domain.com",
  "status": "active"
}

### urlParam example
GET {{baseUrl}}/additional-template-example/100

###
GET {{baseUrl}}/additional-template-example/1

### 
GET {{baseUrl}}/additional-template-example/2

# https://mockoon.com/tutorials/use-environment-variables/
# set the environment variable and restart Mockoon:  export MOCKOON_API_TOKEN=abcd1234
# open Mockoon via command line: open /Applications/Mockoon.app
# the below route is from the other server, start it and this call will get proxied

### you can also run this to set the env var
POST {{baseUrl}}/mockoon-admin/env-vars
Content-Type: application/json

{
  "key": "MOCKOON_API_TOKEN",
  "value": "abcd1234"
}

### test if env vars are working
GET {{baseUrl}}/get-env

### also check out https://mockoon.com/docs/latest/admin-api/environment-variables/
GET {{baseUrl}}/mockoon-admin/env-vars

# https://mockoon.com/tutorials/use-global-variables-state/
### 
POST {{baseUrl}}/login

###
GET {{baseUrl}}/profile

# https://mockoon.com/tutorials/responses-and-rules/
### 
GET {{baseUrl}}

###
GET {{baseUrl}}
authorization: 123123

# https://mockoon.com/tutorials/use-global-variables-state/
# you may have to disable the /* route while testing other routes, because it will block with auth requirement
###
GET {{baseUrl}}/protected

###
GET {{baseUrl}}/protected
authorization: 123123

### reset data buckets
POST {{baseUrl}}/mockoon-admin/data-buckets/purge
