@baseUrl = https://test-api.k6.io
@username = foo
@password = Password-1

###
GET {{baseUrl}}/public/crocodiles/

###
GET {{baseUrl}}/public/crocodiles/1

### change these values if you want to register a new user, I already registered this
# @name registerUser
POST {{baseUrl}}/user/register/ 
Content-Type: application/json

{
    "username": "{{username}}",
    "first_name": "foo_name",
    "last_name": "bar_name",
    "email": "{{username}}@gmail.com",
    "password": "{{password}}"
}

###
# @name login
POST {{baseUrl}}/auth/token/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

