 @baseUrl = https://test-api.k6.io
# to test locally you can run the mockoon app
# and open the mock file in this repo at ./mockoon/crud-croc.json
# or you can use the script that uses mockoon CLI: yarn mock:server
# @baseUrl = http://localhost:3000

@username = Lora28
@password = ugAULkq1S75D0oc
@crocodileId = 13533414


###
# @name getPublicCrocodiles
GET {{baseUrl}}/public/crocodiles/


###
# @name getPublicCrocodile
GET {{baseUrl}}/public/crocodiles/1

### change these values if you want to register a new user, I already registered this
# @name registerUser
POST {{baseUrl}}/user/register/ 
Content-Type: application/json

{
    "username": "Martina_Frami",
    "first_name": "Tyrique",
    "last_name": "Yost",
    "email": "Tess_Hoeger@yahoo.com",
    "password": "Password-1"
}

###
# @name login
POST {{baseUrl}}/auth/token/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###
# @name refreshToken
POST {{baseUrl}}/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "{{login.response.body.refresh}}"
}


###
# @name getMyCrocodiles
GET {{baseUrl}}/my/crocodiles/
Authorization: Bearer {{login.response.body.access}}

###
# @name createCrocodile
POST {{baseUrl}}/my/crocodiles/
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json

{
    "name": "Big Bertha2",
    "sex": "F",
    "date_of_birth": "2019-01-01"
}

###
# @name getMyCrocodile
GET {{baseUrl}}/my/crocodiles/{{crocodileId}}/
Authorization: Bearer {{login.response.body.access}}

###
# @name updateCrocodile
PUT {{baseUrl}}/my/crocodiles/{{crocodileId}}/
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json

{
    "name": "Dustin Schneider",
    "sex": "M",
    "date_of_birth": "2018-10-12",
}

###
# @name patchCrocodile
PATCH {{baseUrl}}/my/crocodiles/{{crocodileId}}/
Authorization: Bearer {{login.response.body.access}}
Content-Type: application/json

{
    "name": "Big Bertha PATCH",
}

###
# @name deleteCrocodile
DELETE {{baseUrl}}/my/crocodiles/{{crocodileId}}/
Authorization: Bearer {{login.response.body.access}}
