name: cy-api-pr
on:
  pull_request:
  workflow_dispatch:

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

env:
  # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.5.0
        with:
          runTests: false

  lint:
    needs: install-dependencies
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.5.0
        with:
          runTests: false
      - name: lint
        run: yarn lint

  typecheck:
    needs: install-dependencies
    name: Run typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.5.0
        with:
          runTests: false
      - name: typecheck
        run: yarn typecheck

  # runnin both dev and local for example's sake, in the real world we would probably only run local here
  cypress-e2e-dev:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome
          config-file: ./cypress/config/dev-config.ts
          # record: true
          # group: dev
          # tag: dev

  cypress-e2e-local:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v6.5.0
        with:
          start: yarn mock:server
          browser: chrome
          config-file: ./cypress/config/local-config.ts
          # record: true
          # group: local
          # tag: local
